sudo: required
addons:
  chrome: stable

dist: xenial

services:
  - xvfb

language: node_js
node_js:
  - "10.15.3"

branches:
  only:
    - master

before_script:
  - export DISPLAY=:99.0
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test

env:
  - YARN_GPG=no

deploy:
  provider: heroku
  api_key:
    secure: 668020fb-9b06-4319-b94c-7e73dfcefb83
  app: thong-automation-heroku
  on:
    repo: thongbk83/excercise
